name: template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  logger: ^2.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.1
  intl: ^0.19.0
  theme_tailor_annotation: ^3.0.1
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  meta: ^1.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  theme_tailor: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/localization/translations
  output_dir: lib/localization/generated

flutter_gen:
  output: lib/asset/generated

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml