name: template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  theme_tailor_annotation: ^2.0.2
  provider: ^6.1.1

  core_architecture:
    path: packages/core_architecture


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  theme_tailor: ^2.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/localization/translations
  output_dir: lib/localization/generated

flutter_gen:
  output: lib/asset/generated

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml